In [113]:
import matplotlib.pyplot as mpl 
import numpy as np 

def mul_matrices(A,B):
    n= np.shape(A)[1]


    if TypeError == len(B[0]) :
        n2=np.shape(B)[0]
    else:
        n2=np.shape(B)[1]
        
    n3=np.shape(B)[0]
    n4=np.shape(A)[0]
    m=np.zeros(shape=(n4,n2))
    if n==n3:
        for j in range(n4):
            for i in range(n2):
                for k in range(n3):
                    m[j][i] += A[j][k]* B[k][i]
        return m
    else:
        return "no se pueden multiplicar las matrices"
         
         
def mul(A,B):
    A = np.array([[-2, 1, 0], [1, -2, 1], [0, 1, -2]])
    B = np.array([-2, 1, 0])

    n = np.shape(A)[1]
    n2 = np.shape(B)[0]
    n3 = np.shape(B)[0]
    n4 = np.shape(A)[0]
    m = np.zeros(shape=(n4, n2))

    if n == n3:
        for j in range(n4):
            for i in range(n2):
                for k in range(n3):
                    m[j][i] += A[j][k] * B[k]
        return m
    else:
        return "no se pueden multiplicar las matrices"



In [107]:

#PUNTO 1 
#a
A1=np.array([[5,-4,-2],[5,-5,4],[2,5,-4],[-5,4,3],[3,-4,-3]])
B1=np.array([[5],[-2],[-3]])
mul1=mul_matrices(A1,B1)
#b
A2=np.array([[0,1,-1,3],[5,-5,-2,2],[1,0,4,5]])
B2=np.array([[0,-3],[-2,-1],[3,-3]])
mul2=mul_matrices(A2,B2)
#c
A3=np.array([[2,-5,5,1],[5,2,-7,-6],[-6,-1,7,4],[5,4,1,-5]])
B3=np.array([[0,4,-7,1,-6],[-1,-6,-5,1,1],[2,-1,-6,5,-5],[-3,-6,6,3,5]])
mul3=mul_matrices(A3,B3)
print(mul3)



[[ 12.  27. -13.  25. -37.]
 [  2.  51. -39. -46. -23.]
 [  3. -49.  29.  40.  20.]
 [ 13.  25. -91.  -1. -56.]]


In [83]:
#PUNTO 2
def reduccion(a,b):
    n=np.shape(a)[0]
    M=np.zeros(shape=(n,n+1))
    
    M[:,0:n] = a
    M[:,n] = b
    for j in range(n-1):
        for i in range(j+1,n):
            coeff=M[i,j]/M[j,j]
            nf=M[i,:]-(coeff*M[j,:])
            M[i,:]=nf
    return M


def solucion (a):
    
    A= a[: , : -1]
    B= a[: ,-1]
    
    n = np.shape(A)[0]
    x = np.zeros(n)
    for i in range(n-1,-1,-1):
        sum = B[i]
        for j in range(n-1,i,-1):
            sum -= A[i,j]*x[j]
        x[i] = sum/A[i,i]

    return x


#Solución de A: Fuerzas
a=np.array([[3,1,-1],[1,-2,1],[4,-1,1]])
b=np.array([2,0,3])
print(solucion(reduccion(a,b))) 
#print(reduccion(a,b)) 
 
# print(np.linalg.solve(a,b))

#Solución de B: Flujo de corriente
A= np.array([[1,1,1],[1,-8,10],[4,-8,0]])
B= np.array([0,0,6])
print(solucion(reduccion(A, B))) 
#print(reduccion(A,B))        

#print(np.linalg.solve(A,B))


[0.71428571 0.85714286 1.        ]
[ 0.75  -0.375 -0.375]


In [114]:
#PUNTO 3

"""
Asumiendo kappa= 1 y m1=m2=m3=1, se tiene la matriz M


"""
M =np.array([[-2,1,0],[1,-2,1],[0,1,-2]])
B =np.array([[1,2,-0.5],[1.006,0,1],[4,-4,5]])


def autovalor_max(m):
    q = np.random.rand(len(m))
    v_max= 0
    
    for i in range(100):
        z=mul_matrices(m, q)
        q=z/np.sqrt(mul_matrices(z.T,z))
        v_max= mul_matrices(q.T,m)
        v_max= mul_matrices(v_max, q)
        
    return v_max

def autovalor_min (m):
    W = np.linalg.inv(m)
    return 1/autovalor_max(W)

#Comprobar los valores propios de la matriz
print(np.linalg.eigvals(M))


print(autovalor_max(M))
print(autovalor_min(M))




[-3.41421356 -2.         -0.58578644]


TypeError: object of type 'numpy.float64' has no len()