In [4]:
import matplotlib.pyplot as mpl 
import numpy as np 

def mul_matrices(A,B):
    n= np.shape(A)[1]
    n2=np.shape(B)[1]
    n3=np.shape(B)[0]
    n4=np.shape(A)[0]
    m=np.zeros(shape=(n4,n2))
    if n==n3:
        for j in range(n4):
            for i in range(n2):
                for k in range(n3):
                    m[j][i] += A[j][k]* B[k][i]
        return m
    else:
        return "no se pueden multiplicar las matrices"
         



In [5]:

# punto 1 
#a
A1=np.array([[5,-4,-2],[5,-5,4],[2,5,-4],[-5,4,3],[3,-4,-3]])
B1=np.array([[5],[-2],[-3]])
mul1=mul_matrices(A1,B1)
#b
A2=np.array([[0,1,-1,3],[5,-5,-2,2],[1,0,4,5]])
B2=np.array([[0,-3],[-2,-1],[3,-3]])
mul2=mul_matrices(A2,B2)
#c
A3=np.array([[2,-5,5,1],[5,2,-7,-6],[-6,-1,7,4],[5,4,1,-5]])
B3=np.array([[0,4,-7,1,-6],[-1,-6,-5,1,1],[2,-1,-6,5,-5],[-3,-6,6,3,5]])
mul3=mul_matrices(A3,B3)



In [42]:
#punto 2.
def reduccion(a,b):
    n=np.shape(a)[0]
    M=np.zeros(shape=(n,n+1))
    M[:,0:n] = a
    M[:,n] = b
    for j in range(n-1):
        for i in range(j+1,n):
            coeff=M[i,j]/M[j,j]
            nf=M[i,:]-(coeff*M[j,:])
            M[i,:]=nf
    return M
a=np.array([[3,1,-1],[1,-2,1],[4,-1,1]])
b=np.array([2,0,3])


def solucion (a):
    n = np.shape(a)[0]
    sol = np.zeros(n)
    for i in range(n-1,-1,-1):
        des=0
        for j in range(i+1,n): # j o i?
            des += a[i,j]*sol[i]
            
    return des,sol

print(solucion(reduccion(a,b)))        




(0.0, array([0., 0., 0.]))


In [43]:
np.linalg.solve(a,b)

array([0.71428571, 0.85714286, 1.        ])

In [41]:
def reduccion(a):
    n=len(a)
    for j in range(n-1):
        for i in range(j+1,n):
            coeff=a[i,j]/a[j,j]
            nf=a[i,:]-(coeff*a[j,:])
            a[i,:]=nf
    return a

a=np.array([[3,1,-1,2],[1,-2,1,0],[4,-1,1,3]])
print(reduccion(a))

[[ 3  1 -1  2]
 [ 0 -2  1  0]
 [ 0  0  1  0]]


In [57]:
#PUNTO 3

M =np.array([[1,2,-0.5],[1.006,0,1],[4,-4,5]])

#q =np.array([1,2,1])

def autovalor_max(m):
    q = np.random.rand(len(m))
    v_max= 0
    
    for i in range(100):
        z=np.matmul(m,q)
        q=z/np.sqrt(np.matmul(z.T,z))
        v_max= np.matmul(q.T,m)
        v_max= np.matmul(v_max, q)
        
    return v_max

def autovalor_min (m):
    W = np.linalg.inv(m)
    return 1/autovalor_max(W)

#Comprobar los valores propios de la matriz
print(np.linalg.eigvals(M))

print(autovalor_max(M))
print(autovalor_min(M))




4.0
0.8904554884413486
