In [41]:
import matplotlib.pyplot as plt 
import numpy as np


In [2]:
#Punto 4
def mul_matrices(A,B):
    A = np.array([[-2, 1, 0], [1, -2, 1], [0, 1, -2]])
    B = np.array([-2, 1, 0])

    n = np.shape(A)[1]
    n2 = np.shape(B)[0]
    n3 = np.shape(B)[0]
    n4 = np.shape(A)[0]
    m = np.zeros(shape=(n4, n2))

    if n == n3:
        for j in range(n4):
            for i in range(n2):
                for k in range(n3):
                    m[j][i] += A[j][k] * B[k]
        return m
    else:
        return "no se pueden multiplicar las matrices"

In [4]:
#Punto 7
def sor(A,b,x0,w,itmax=1000,tolerancia=1e-14):
    x=x0.copy()
    sum_k= x.copy()
    residuo = np.linalg.norm( np.dot(A,x) - b)
    it=0
    while residuo>= tolerancia and it < itmax:
    
        sum_k[:]=0
        
        for i in range (A.shape[0]):
            for j in range (A.shape[1]):
                if i != j:
                     sum_k[i] += A[i][j] * x[j]
            x[i] = (1 - w) * x[i] + (w / A[i][i]) * (b[i] - sum_k[i])
        
        residuo = np.linalg.norm(np.dot(A, x) - b)
        it += 1
        
        if residuo > 1000:
            print('No calculable con SOR')
            x[:] = 0.
            break
    
        
    return x,it
def omega_optimo(A,b,x0,itmax=1000,tolerancia=1e-14):
    w=None
    iteracion_minima=float('inf')
    for w0 in range(1,2):
        metodo= sor(A,b,x0,itmax,tolerancia)
        iteracion=len(metodo)
        
        if iteracion< iteracion_minima:
            iteracion_minima=iteracion
            w=w0   
    return w
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])
w=omega_optimo(A,b,np.array([0,0,0]))
x=sor(A,b,np.array([0,0,0]),w)
x

No calculable con SOR


(array([1, 1, 1]), 2)

In [15]:
# punto 11 

H= np.array([[1,2,-1],[1,0,1],[4,-4,5]])


def autovalor_min (m):
    W = np.linalg.inv(m)
    
    q = np.random.rand(len(W))
    n=np.shape(W)[0]
    
    q1=np.zeros(shape=(n,1))
    for i in range(len(q)):
        q1[i][0]= q[i]
        
    for i in range(100):
        z= np.dot(W, q1)
        q1= z/np.sqrt(np.dot(z.T,z))
        valor_min= np.dot(q1.T,W)
        valor_min= np.dot(valor_min, q1)
    return "El valor de estado base E0 es "+ str(1/valor_min) + " y su vector propio es " + str(q1).replace("\n", " ")
autovalor_min(H)


'El valor de estado base E0 es [[1.]] y su vector propio es [[-0.40824829]  [ 0.40824829]  [ 0.81649658]]'

In [79]:
#Punto 12a

# Por descenso al gradiente 
def funcion_1(x,y):
    f1=((np.log(x**2+y**2)-np.sin(x*y))-(np.log(2)+np.log(np.pi)))
    f2=(np.exp(x-y)+np.cos(x*y))
    return f1**2+f2**2

Dx = lambda f,x,y,h=1e-5: (f(x+h,y) - f(x-h,y))/(2*h)
Dy = lambda f,x,y,h=1e-5: (f(x,y+h) - f(x,y-h))/(2*h)
x0, y0 = 0.5,0.1
Gradient = lambda f,x,y: np.array([Dx(f,x,y),Dy(f,x,y)])
def Minimizer(f, N = 100, gamma = 0.01):
    
    r = np.zeros((N,2))
    r[0] = np.random.uniform(-5.,5.,size=2)
    
    Grad = np.zeros((N,2))
    Grad[0] = Gradient(f,r[0,0],r[0,1])
    
    for i in (range(1,N)):
        r[i] = r[i-1] - gamma*Gradient(f,r[i-1,0],r[i-1,1])
        Grad[i] = Gradient(f,r[i-1,0],r[i-1,1])
        
        
    return r,Grad
N = 200
r,Grad = Minimizer(funcion_1,N)
r[-1]

#por Newton-Raphson
G1= np.array([lambda x,y:(np.log(x**2+y**2)-np.sin(x*y))-(np.log(2)+np.log(np.pi)),
              lambda x,y: np.exp(x-y)+np.cos(x*y)])

def GetF(G,r):
    
    n = r.shape[0]
    
    v = np.zeros_like(r)
    
    for i in range(n):
        v[i] = G[i](r[0],r[1])
        
    return v
def GetJacobian(f,r,h=1e-6):
    
    n = r.shape[0]
    
    J = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            
            rf = r.copy()
            rb = r.copy()
            
            rf[j] = rf[j] + h
            rb[j] = rb[j] - h
            
            J[i,j] = ( f[i](rf[0],rf[1]) - f[i](rb[0],rb[1])  )/(2*h)
            
    
    return J

def NewtonRaphson(G,r,itmax=1000,error=1e-9):
    
    it = 0
    d = 1.
    dvector = []
    
    while d > error and it < itmax:
        
        # Vector actual
        rc = r
        
        F = GetF(G,rc)
        J = GetJacobian(G,rc)
        InvJ = np.linalg.inv(J)
        
        r = rc - np.dot(InvJ,F)
        
        diff = r - rc
        
        d = np.max( np.abs(diff) )
        
        dvector.append(d)
        print(dvector)
        
        it += 1
    
    print(it)
    return r,dvector


r2,dvector = NewtonRaphson(G1,np.array([0.,0.]))
r2


<ipython-input-79-089659c5e229>:32: RuntimeWarning: divide by zero encountered in log
  G1= np.array([lambda x,y:(np.log(x**2+y**2)-np.sin(x*y))-(np.log(2)+np.log(np.pi)),


LinAlgError: Singular matrix

In [64]:
#Punto 12b 
G2 = np.array([lambda x,y,z: 6*x - 2*np.cos(y*z) - 1.,
     lambda x,y,z: 9*y + np.sqrt( x**2 + np.sin(z) + 1.06 ) + 0.9,
     lambda x,y,z: 60*z + 3*np.exp(-x*y)+10*np.pi - 3])

#Usando Newton Rhapson para este sistema 


def GetF(G,r):
    
    n = r.shape[0]
    
    v = np.zeros_like(r)
    
    for i in range(n):
        v[i] = G[i](r[0],r[1],r[2])
        
    return v
def GetJacobian(f,r,h=1e-6):
    
    n = r.shape[0]
    
    J = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            
            rf = r.copy()
            rb = r.copy()
            
            rf[j] = rf[j] + h
            rb[j] = rb[j] - h
            
            J[i,j] = ( f[i](rf[0],rf[1],rf[2]) - f[i](rb[0],rb[1],rb[2])  )/(2*h)
            
    
    return J
def NewtonRaphson(G,r,itmax=1000,error=1e-9):
    
    it = 0
    d = 1.
    dvector = []
    
    while d > error and it < itmax:
        
        # Vector actual
        rc = r
        
        F = GetF(G,rc)
        J = GetJacobian(G,rc)
        InvJ = np.linalg.inv(J)
        
        r = rc - np.dot(InvJ,F)
        
        diff = r - rc
        
        d = np.max( np.abs(diff) )
        
        dvector.append(d)
        print(dvector)
        
        it += 1
    
    return r,dvector
r,dvector=NewtonRaphson(G2,np.array([0.,0.,0.]))
print (r)
# Con descenso al gradiente 

def funcion(x,y,z):
    f1= (6*x - 2*np.cos(y*z) - 1.)
    f2= 9*y + np.sqrt( x**2 + np.sin(z) + 1.06 ) + 0.9
    f3=60*z + 3*np.exp(-x*y)+10*np.pi - 3
    return f1**2+f2**2+f3**2

Dx = lambda f,x,y,z,h=1e-5: (f(x+h,y,z) - f(x-h,y,z))/(2*h)
Dy = lambda f,x,y,z,h=1e-5: (f(x,y+h,z) - f(x,y-h,z))/(2*h)
Dz = lambda f,x,y,z,h=1e-5: (f(x,y,z+h) - f(x,y,z-h))/(2*h)

x0,y0,z0= 0.7,0.5,0.1

Gradient = lambda f,x,y,z: np.array([Dx(f,x,y,z),Dy(f,x,y,z),Dz(f,x,y,z)]) 

def Minimizer(f, N = 100, gamma = 0.01):
    
    r = np.zeros((N,3))
    r[0] = np.random.uniform(-10.,10.,size=3)
    
    Grad = np.zeros((N,3))
    Grad[0] = Gradient(f,r[0,0],r[0,1],r[0,2])
    for i in (range(1,N)):
        r[i] = r[i-1] - gamma*Gradient(f,r[i-1,0],r[i-1,1],r[i-1,2])
        Grad[i] = Gradient(f,r[i-1,0],r[i-1,1],r[i-1,2])
        
        
    return r,Grad
    
N = 200
rd,Grad = Minimizer(funcion,N)
rd[-1]


[0.5235987756181211]
[0.5235987756181211, 0.013464494608999344]
[0.5235987756181211, 0.013464494608999344, 1.3125552370152338e-05]
[0.5235987756181211, 0.013464494608999344, 1.3125552370152338e-05, 7.48751061152575e-12]
[ 0.49814468 -0.1996059  -0.52882598]


<ipython-input-64-b8ba91b944ec>:72: RuntimeWarning: overflow encountered in exp
  f3=60*z + 3*np.exp(-x*y)+10*np.pi - 3
<ipython-input-64-b8ba91b944ec>:75: RuntimeWarning: invalid value encountered in double_scalars
  Dx = lambda f,x,y,z,h=1e-5: (f(x+h,y,z) - f(x-h,y,z))/(2*h)
<ipython-input-64-b8ba91b944ec>:76: RuntimeWarning: invalid value encountered in double_scalars
  Dy = lambda f,x,y,z,h=1e-5: (f(x,y+h,z) - f(x,y-h,z))/(2*h)
<ipython-input-64-b8ba91b944ec>:77: RuntimeWarning: invalid value encountered in double_scalars
  Dz = lambda f,x,y,z,h=1e-5: (f(x,y,z+h) - f(x,y,z-h))/(2*h)


array([nan, nan, nan])

In [70]:
#Punto 17

import sympy as sym

x = sym.Symbol('x',real=True)
y = sym.Symbol('y',real=True)
z = x + sym.I*y

def f(x,y,z):

    f = z**3 + 1
    f = f.expand()
    return sym.re(f),sym.im(f)

f_re,f_im = f(x,y,z)
F = [f_re,f_im]

J = sym.zeros(2,2)

for i in range(2):
    for j in range(2):
        if j==0:
            J[i,j] = sym.diff(F[i],x,1)
        else:
            J[i,j] = sym.diff(F[i],y,1)

J

Fn = sym.lambdify([x,y],F,'numpy')
Jn = sym.lambdify([x,y],J,'numpy')
InvJ = J.inv(method='LU')
InvJ

def raiz(z,Fn,Jn,itmax=100,precision=1e-7):
    #Se invierte el Jacobiano
    InvJ = Jn.inv(method='LU')
    IJn = sym.lambdify([x,y],InvJ,'numpy')
    InvJ
    
    error = 1
    it = 0
    
    while error > precision and it < itmax:
        IFn = Fn(z[0],z[1])
        InJn = IJn(z[0],z[1])
        z1 = z- np.dot(InJn,IFn)
        
        error = np.max( np.abs(z1-z) )
        z= z1
        it +=1
        
    return z

z0= np.array([0.5 , 0.6])
zsol= raiz(z0,Fn,J)
zsol

N= 300
x = np.linspace(-1, 1, N)
y = np.linspace(-1, 1, N)

1


<lambdifygenerated-3>:2: RuntimeWarning: divide by zero encountered in double_scalars
  return (array([[(-36*x**2*y**2/((3*x**2 - 3*y**2)*(36*x**2*y**2/(3*x**2 - 3*y**2) + 3*x**2 - 3*y**2)) + 1)/(3*x**2 - 3*y**2), 6*x*y/((3*x**2 - 3*y**2)*(36*x**2*y**2/(3*x**2 - 3*y**2) + 3*x**2 - 3*y**2))], [-6*x*y/((3*x**2 - 3*y**2)*(36*x**2*y**2/(3*x**2 - 3*y**2) + 3*x**2 - 3*y**2)), (36*x**2*y**2/(3*x**2 - 3*y**2) + 3*x**2 - 3*y**2)**(-1.0)]]))
<lambdifygenerated-3>:2: RuntimeWarning: invalid value encountered in double_scalars
  return (array([[(-36*x**2*y**2/((3*x**2 - 3*y**2)*(36*x**2*y**2/(3*x**2 - 3*y**2) + 3*x**2 - 3*y**2)) + 1)/(3*x**2 - 3*y**2), 6*x*y/((3*x**2 - 3*y**2)*(36*x**2*y**2/(3*x**2 - 3*y**2) + 3*x**2 - 3*y**2))], [-6*x*y/((3*x**2 - 3*y**2)*(36*x**2*y**2/(3*x**2 - 3*y**2) + 3*x**2 - 3*y**2)), (36*x**2*y**2/(3*x**2 - 3*y**2) + 3*x**2 - 3*y**2)**(-1.0)]]))


array([nan, nan])